### ISSUE TITLE
Please fix your k8s manifests

### ISSUE THREAD

**Issue by robrsprd** [fluent/fluent-bit-kubernetes-logging#10]
My team just came from the open source summit and was quite excited about what they heard about fluentbit running in a k8s. Reason enough for me to have a deeper look as the idea of enriched logs promises some very cool use-cases. BUT there are some very annoying issues within this repo:
* The manifest in the docs and in this repo don't match
* The image used here inside the daemonset-yaml is not the "official" image from docker hub
* Image tags from "vanilla" fluentbit and for the fluentbit daemonset are out of sync. Actually the is no further need to push separate images anymore since you now provide the additional config for k8s within a configmap. It might also be a good idea to move this into the examples-section of the original fluentbit repository.
* I really appreciate the usage of configmaps but you then should also mount it into your pods and indent it correctly
* The name of the created service-account for RBAC-setup does not match the one consumed by the daemonset

But after fixing all those minor issues i was very pleased with the result, as the application itself does a great job :)

**Comment by edsiper** [comment]
@robrsprd 

first of all I am glad your team was able to assist and enjoyed the talk. 

Regarding this repo, yesterday I started a re-do of it so you will see some changes today with more updated/aligned information. 

thanks for your feedback :)

**Comment by edsiper** [comment]
@robrsprd 

All the content have been updated. Would you please review it ?

https://github.com/fluent/fluent-bit-kubernetes-logging

**Comment by edsiper** [comment]
Since content have been updated and tested locally, I am closing this issue as fixed.
