### ISSUE TITLE
Container logs broken symlinks

### ISSUE THREAD

**Issue by jordanwu97** [fluent/fluent-bit-kubernetes-logging#26]
The logs at `/var/log/containers/*.log` will end up referencing files in `/var/data` on my k8s cluster (v1.9.7), which is not mounted by the DaemonSet and results in broken symlinks. Workaround is to just mount `/var` as a whole.

**Comment by kaybinwong** [comment]
+1

**Comment by orenzp** [comment]
@jordanwu97 I can't believe i missed that your a life saver. On my cluster (VMWare PKS) the `/var/log/containers/*log` is kinking to /var/pods for some reason.

**Comment by edsiper** [comment]
is the configmap broken or a custom config in the kubernetes environment from the provider don't match our configmap ?

**Comment by jordanwu97** [comment]
I was working on a IBM Kubernetes Service. Not sure if this was just an issue for the specific environment. Closing for now.
