### ISSUE TITLE
Getting HTTP post in ELK from Fluent-bit

### ISSUE THREAD

**Issue by orenzp** [fluent/fluent-bit-kubernetes-logging#54]
Hi 
I finished setting up the solution and i getting entries like the ones that you can see in the attached picture. they seem to be regular HTTP post headers. 

Does anyone how to filter them out? or if this is a normal setup?

![error](https://user-images.githubusercontent.com/25840401/61062412-dd3c8200-a406-11e9-9762-9e550ed10c90.jpg)

Thanks in advance for all the help and the project.

**Comment by edsiper** [comment]
you should disable debug/trace mode otherwise you will get that info in your logs.
