### ISSUE TITLE
How to exclude Kubernetes namespace

### ISSUE THREAD

**Issue by orenzp** [fluent/fluent-bit-kubernetes-logging#55]
Hi
Is there a way to exclude certain namespaces in fluet-bit? I would like to exclude certain namespaces so that fluent bit doesn't forward all logs created in those namespaces to ELK.

Is there a way to do it besides adding annotation to each pod in that namespace? Im aware that you can run Kubectl annotation to update all the pod in a namespace with a new annotation. 

Thanks in advance for your support and maintaining this project.

**Comment by imranrazakhan** [comment]
@orenzp Have you able to fix this issue?
