### ISSUE TITLE
Need to include `LICENSE` on this repo

### ISSUE THREAD

**Issue by dncarley** [fluent/fluent-bit-kubernetes-logging#72]
Need to include `LICENSE` on this repo.

Expect to be Apache License 2.0

as used on 

 - https://github.com/fluent/fluent-bit/blob/master/LICENSE
 - https://github.com/fluent/fluent-bit-docker-image/blob/master/LICENSE

and the similar `fluentd-kubernetes-daemonset`:

https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/LICENSE

**Comment by dncarley** [comment]
Fluent org needs to confirm if any source contained within this repo does not align with Apache License 2.0.

**Comment by agup006** [comment]
Quite late here, I've gone ahead and added the Apache License 2.0
