### ISSUE TITLE
No matches for kind "DaemonSet" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by CAlexPac** [fluent/fluent-bit-kubernetes-logging#77]
The DaemonSet config file for Elasticsearch needs to be updated.
According to https://github.com/gluster/gluster-kubernetes/issues/627 "extensions/v1beta1" has to be replaced with apps/v1

**Comment by gabegorelick** [comment]
See https://github.com/fluent/fluent-bit-kubernetes-logging/issues/59

**Comment by gabegorelick** [comment]
Also, this was fixed in https://github.com/fluent/fluent-bit-kubernetes-logging/pull/81.
